### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by AnthonyChraim**
Added 6 unit tests for delivery 2 core features

### CODE REVIEW

**Comment by car12lin12** [comment]
Nicely done

**Review by car12lin12 — APPROVED** [review]

**Comment by Sebastien0730** [comment]
Can you move your test folder to where the other tests are please.

**Comment by AnthonyChraim** [comment]
Don't see the point in moving them since that's where they're supposed to be. The other folder isn't marked as a test folder and where you generate the tests automatically, that's where IntelliJ puts them

**Comment by AnthonyChraim** [comment]
I can move the other ones to this file though but Nafisa told me they need to be updated

**Comment by Sebastien0730** [comment]
Ah ok, yeah move the old one to the new folder, and maybe mark them as ignored?

**Comment by Sebastien0730** [comment]
Nice thanks 👍

**Pull request merged**
